name: 'naughty-compose'
description: 'Learning Jetpack Compose'
author: 'Muhammad Faisal Amir'
branding:
  icon: archive
  color: green
inputs:
  myInput:
    description: 'Input to use'
    required: false
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
